watchdog/Server/Log/models.py
import time
import re

from watchdog.Server.Database import connection, dictFactory


@connection
def createLog(Puppy_Name, LogLevel_idLevel, Message,  **kwargs):
    result = 'OK'
    try:
        conn = kwargs['conn']
        sql = 'INSERT INTO Log (Puppy_Name, LogLevel_idLevel, Timestamp, Message) VALUES (?,?,?,?)'
        params = (Puppy_Name, LogLevel_idLevel, int(time.time()), Message)
        conn.execute(sql,params)
        conn.commit()
    except Exception as e:
        result = str(e)
    finally:
        return result


@connection
def deleteLog(idLog, **kwargs):
    result = 'OK'
    try:
        conn = kwargs['conn']
        sql = gen_delete_sql('Log','idLog',idLog)
        conn.execute(sql)
        conn.commit()
    except Exception as e:
        result = str(e)
    finally:
        return result


@connection
@dictFactory
def getLogs(*args, **kwargs):
    return kwargs['conn'].execute('select * from Log')


@connection
@dictFactory
def getLog(Puppy_Name, *args, **kwargs):
    return kwargs['conn'].execute('select * from Log WHERE Puppy_Name=?', (Puppy_Name,))


def get_match(pattern,text):
    a = re.search(pattern,text)
    if a:
        return a.group()
    else:
        return None

def gen_delete_sql(tableName, column, in_text):
    in_text = in_text.replace(" ","")
    sql_prefix = 'DELETE FROM {table} WHERE '.format(table=tableName)
    condition = ''
    
    empty = "^(?![\s\S])" # for empty
    single = "^\d+$" # single values
    num_list = "^\d+(,{1}\d+)+$" # list of numbers
    between = "^\d+-{1}\d+$" # between
    comparative = "^[<>]{1}\d+" # comparative
    
    # ignore emty strings (safety check lol)
    if get_match(empty,in_text):
        return None
    
    a = get_match(single,in_text)
    b = get_match(num_list,in_text)
    c = get_match(between,in_text)
    d = get_match(comparative,in_text)
    # get in values
    if a or b:
        condition =  '{column} IN ({condition})'.format(column=column, condition= a or b)
    elif c:
        num1, num2 = c.split('-')
        condition =  '{column} >= {num1} AND {column} <= {num2}'.format(column=column, num1=num1, num2=num2)
    elif d:
        num = d[1:]
        operator = d[:1]
        condition =  '{column} {operator} {num}'.format(column=column, operator=operator, num=num)
    else:
        return None
    
    return sql_prefix + condition

watchdog/Server/Task/models.py
import time

from watchdog.Server.Database import connection, dictFactory


@connection
def createTask(Puppy_Name, LogLevel_idLevel, Job,  **kwargs):
    result = 'OK'
    try:
        conn = kwargs['conn']
        sql = 'INSERT INTO Task (Puppy_Name, LogLevel_idLevel, Job) VALUES (?,?,?)'
        params = (Puppy_Name, LogLevel_idLevel, Job)
        conn.execute(sql,params)
        conn.commit()
    except Exception as e:
        result = str(e)
    finally:
        return result


@connection
def deleteTask(idTask, **kwargs):
    result = 'OK'
    try:
        conn = kwargs['conn']
        sql = 'DELETE FROM Task WHERE idTask = ?'
        params = (idTask,)
        conn.execute(sql,params)
        conn.commit()
    except Exception as e:
        result = str(e)
    finally:
        return result


@connection
@dictFactory
def getTasks(*args, **kwargs):
    return kwargs['conn'].execute('select * from Task')


@connection
@dictFactory
def getTask(Puppy_Name, *args, **kwargs):
    return kwargs['conn'].execute('select * from Task WHERE Puppy_Name=?', (Puppy_Name,))

watchdog/Server/Log/__init__.py
from .views import log
from .models import createLog, getLog, getLogs, deleteLog

watchdog/Server/Log/views.py
from flask import session, redirect, Blueprint, render_template, request, jsonify, abort


from watchdog.Server.Auth import authHandler
from .models import createLog, getLog, getLogs, deleteLog
from  watchdog.Utils import check_bad_request


log = Blueprint('log', __name__, template_folder='templates')


@log.route('/', methods=['GET', 'POST'])
@authHandler
def log_get_set():
	if request.method == 'GET':
		if request.args.get('name', None):
			Name = request.args.get('name')
			return jsonify(getLog(Name))
		else:
			return jsonify(getLogs())

	elif request.method == 'POST':
		# check for form contents
		Name = request.form.get('PuppyName',None)
		Level = request.form.get('LogLevel',None)
		Message = request.form.get('Message',None)
		check_bad_request(Name, Level, Message)
		result =  createLog(Name, Level, Message)
		return render_template('message.html', message=result)

	else:
		abort(405)


@log.route('/delete', methods=['GET', 'POST'])
@authHandler
def log_del():
	if request.method == 'GET':
		return render_template('delete_log.html')
	else:
		log_id = request.form.get('logId',None)
		check_bad_request(log_id)
		result = deleteLog(log_id)
		return render_template('message.html', message=result)

@log.route('/create', methods=['GET'])
@authHandler
def create_log_page():
	return render_template('create_log.html')

watchdog/Server/Puppy/views.py
from flask import session, redirect, Blueprint, render_template, request, jsonify, abort


from watchdog.Server.Auth import authHandler
from .models import createPuppy, getPuppies, getPuppy, deletePuppy
from  watchdog.Utils import check_bad_request

puppy = Blueprint('puppy', __name__, template_folder='templates')



@puppy.route('/', methods=['GET', 'POST'])
@authHandler
def puppy_get_set():
	if request.method == 'GET':
		if request.args.get('name', None):
			Name = request.args.get('name')
			return jsonify(getPuppy(Name, Tasks=True, Logs=True))
		else:
			return jsonify(getPuppies())

	elif request.method == 'POST':
		# check for form contents
		Name = request.form.get('PuppyName',None)
		Token = request.form.get('PuppyToken',None)
		Method = request.form.get('PuppyMethod',None)
		NotifyInterval = request.form.get('PuppyNotPer',None)
		check_bad_request(Name, Token, Method, NotifyInterval)
		result = createPuppy(Name, Token, Method, NotifyInterval)
		return render_template('message.html', message=result)
	else:
		abort(405)


@puppy.route('/delete', methods=['GET','POST'])
@authHandler
def puppy_del():
	if request.method == 'GET':
		return render_template('delete_puppy.html')
	else:
		Name = request.form.get('name',None)
		check_bad_request(Name)
		result = deletePuppy(Name)
		return render_template('message.html', message=result)

@puppy.route('/create', methods=['GET'])
@authHandler
def create_puppy_page():
	return render_template('create_puppy.html')

watchdog/Server/Task/__init__.py
from .views import task
from .models import getTask

watchdog/Server/Task/views.py
from flask import session, redirect, Blueprint, render_template, request, jsonify, abort


from watchdog.Server.Auth import authHandler
from .models import createTask, getTask, getTasks, deleteTask
from  watchdog.Utils import check_bad_request


task = Blueprint('task', __name__, template_folder='templates')


@task.route('/', methods=['GET', 'POST'])
@authHandler
def task_get_set():
	if request.method == 'GET':
		if request.args.get('name', None):
			Name = request.args.get('name')
			return jsonify(getTask(Name))
		else:
			return jsonify(getTasks())

	elif request.method == 'POST':
		# check for form contents
		Name = request.form.get('PuppyName',None)
		Level = request.form.get('LogLevel',None)
		Job = request.form.get('Job',None)
		check_bad_request(Name, Level, Job)
		result = createTask(Name, Level, Job)
		return render_template('message.html', message=result)

	else:
		abort(405)


@task.route('/delete', methods=['GET', 'POST'])
@authHandler
def task_del():
	if request.method == 'GET':
		return render_template('delete_task.html')
	else:
		task_id = request.form.get('taskId',None)
		check_bad_request(task_id)
		result = deleteTask(task_id)
		return render_template('message.html', message=result)


@task.route('/create', methods=['GET'])
@authHandler
def create_task_page():
	return render_template('create_task.html')

watchdog/Server/templates/includes/footer.html
<footer class="page-footer font-small blue">

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="mailto:cabayaratne@gmail.com"> Chamal Abayaratne</a>
  </div>
  <!-- Copyright -->

</footer>

watchdog/Server/templates/includes/logs.html
<h4>All Logs</h4>
<table id="LogsTable"  class="table table-striped table-bordered" style="width:100%"></table>

<script type="text/javascript">
var xmlhttp = new XMLHttpRequest();
var url = "{{ url_for('log.log_get_set') }}";
var method = 'GET';



xmlhttp.onreadystatechange = function() {
    if (this.readyState == 4 && this.status == 200) {
        var myArr = JSON.parse(this.responseText);

        for (let i of myArr) {
            i.Timestamp = unixToTimestr(i.Timestamp);
        }

        logsFunction(myArr);
    }
};

xmlhttp.open(method, url, true);
xmlhttp.send();

function logsFunction(arr) {
    var logs_table = $('#LogsTable').DataTable(
    	{
    		data: arr,
    		"pageLength": 10,
    		// "lengthChange": false,
    		columns: [
    		{ data: 'idLog' ,title:'Id'},
    		{ data: 'Puppy_Name' ,title:'Pup name'},
    		{ data: 'LogLevel_idLevel' ,title:'Level'},
            { data: 'Timestamp' ,title:'Timestamp'},
            { data: 'Message' ,title:'Message'},
    		]
    	});

    $(logs_table.table().header().rows).clone(true).appendTo( logs_table.table().header() );
    $(logs_table.table().header().rows[1].cells).each( function (i) {
        var title = $(this).text();
        $(this).html( '<input class="form-control form-control-sm" type="text" placeholder="Search '+title+'" />' );
 
        $( 'input', this ).on( 'keyup change', function () {
            if ( logs_table.column(i).search() !== this.value ) {
                logs_table
                    .column(i)
                    .search( this.value )
                    .draw();
            }
        } );
    } );

    
    logs_table.column(0).order('desc');
    logs_table.draw()
}

function unixToTimestr(unixTime) {
    /*
    This function converts unix timestamp to m2l5 signal styled
    remember to offset the time diffeence
    */
    let time_diff = new Date().getTimezoneOffset()*60;
    let date_obj = new Date((unixTime+time_diff)*1000);

    let year = date_obj.getFullYear();
    let month = String(date_obj.getMonth()+1).padStart(2,0);
    let date = String(date_obj.getDate()).padStart(2,0);
    let hour = String(date_obj.getHours()).padStart(2,0);
    let minute = String(date_obj.getMinutes()).padStart(2,0);
    let second = String(date_obj.getSeconds()).padStart(2,0);
    return `${year}-${month}-${date} ${hour}:${minute}:${second}`;
}

</script>

watchdog/Server/templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">

	<!-- <a class="navbar-brand" href="{{ url_for('admin') }}">Watchdog</a> -->


	{% if session.get('logged_in') %}
	  <a class="navbar-brand" href="{{ url_for('admin') }}">
    <img src="/static/img/logo.jpg" height="30" class="d-inline-block align-top" alt="">
    
  	</a>
	
	<div class="collapse navbar-collapse" id="navbarNav">
		<ul class="navbar-nav mr-auto">


			<li class="nav-item">
				<a class="nav-link" href="{{ url_for('puppy.create_puppy_page') }}">+Create Puppy</a>
			</li>

			<li class="nav-item">
				<a class="nav-link" href="{{ url_for('task.create_task_page') }}">+Create Task</a>
			</li>

			<li class="nav-item">
				<a class="nav-link" href="{{ url_for('puppy.puppy_del') }}">-Delete Puppy</a>
			</li>

			<li class="nav-item">
				<a class="nav-link" href="{{ url_for('task.task_del') }}">-Delete Task</a>
			</li>

			<li class="nav-item">
				<a class="nav-link" href="{{ url_for('log.log_del') }}">-Delete Log</a>
			</li>

		</ul>

		<ul class="navbar-nav mr-auto">

			<li class="nav-item">
				<a class="nav-link" href="#">Server time: {{today_date}}    </a>
			</li>
		</ul>

		<ul class="navbar-nav ml-auto">



			<li class="nav-item">
				<a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
			</li>

		</ul>
	</div>
	{% endif %}



</nav>

watchdog/Server/templates/includes/puppies.html
<h4>All Puppies</h4>
<table id="PuppiesTable"  class="table table-striped table-bordered" style="width:100%"></table>


<script type="text/javascript">
var xmlhttp = new XMLHttpRequest();
var url = "{{ url_for('puppy.puppy_get_set') }}";
var method = 'GET';

xmlhttp.onreadystatechange = function() {
    if (this.readyState == 4 && this.status == 200) {
        var myArr = JSON.parse(this.responseText);

        for (let i of myArr) {
            i.ReportLast = unixToTimestr(i.ReportLast);
            i.NotifyLast = unixToTimestr(i.NotifyLast);
        }
        
        puppiesFunction(myArr);
    }
};

xmlhttp.open(method, url, true);
xmlhttp.send();

function puppiesFunction(arr) {
    var puppies_table = $('#PuppiesTable').DataTable(
    	{
    		data: arr,
    		"pageLength": 10,
    		// "lengthChange": false,
    		columns: [
    		{ data: 'Name' ,title:'Name'},
    		{ data: 'Token' ,title:'Token'},
    		{ data: 'Method' ,title:'Method'},
            { data: 'ReportInterval' ,title:'Report interval'},
            { data: 'ReportLast' ,title:'Report last'},
            { data: 'NotifyInterval' ,title:'Notify interval'},
            { data: 'NotifyLast' ,title:'Notify last'},
    		]
    	});

    $(puppies_table.table().header().rows).clone(true).appendTo( puppies_table.table().header() );
    $(puppies_table.table().header().rows[1].cells).each( function (i) {
        var title = $(this).text();
        $(this).html( '<input class="form-control form-control-sm" type="text" placeholder="Search '+title+'" />' );
 
        $( 'input', this ).on( 'keyup change', function () {
            if ( puppies_table.column(i).search() !== this.value ) {
                puppies_table
                    .column(i)
                    .search( this.value )
                    .draw();
            }
        } );
    } );

    puppies_table.draw()
}

function unixToTimestr(unixTime) {
    /*
    This function converts unix timestamp to m2l5 signal styled
    remember to offset the time diffeence
    */
    let time_diff = new Date().getTimezoneOffset()*60;
    let date_obj = new Date((unixTime+time_diff)*1000);

    let year = date_obj.getFullYear();
    let month = String(date_obj.getMonth()+1).padStart(2,0);
    let date = String(date_obj.getDate()).padStart(2,0);
    let hour = String(date_obj.getHours()).padStart(2,0);
    let minute = String(date_obj.getMinutes()).padStart(2,0);
    let second = String(date_obj.getSeconds()).padStart(2,0);
    return `${year}-${month}-${date} ${hour}:${minute}:${second}`;
}

</script>

watchdog/Server/templates/includes/tasks.html
<h4>All Tasks</h4>
<table id="TasksTable"  class="table table-striped table-bordered" style="width:100%"></table>

<script type="text/javascript">
var xmlhttp = new XMLHttpRequest();
var url = "{{ url_for('task.task_get_set') }}";
var method = 'GET';

xmlhttp.onreadystatechange = function() {
    if (this.readyState == 4 && this.status == 200) {
        var myArr = JSON.parse(this.responseText);
        tasksFunction(myArr);
    }
};

xmlhttp.open(method, url, true);
xmlhttp.send();

function tasksFunction(arr) {
    var tasks_table = $('#TasksTable').DataTable(
    	{
    		data: arr,
    		pageLength: 10,
    		// lengthChange: false,
    		columns: [
    		{ data: 'idTask' ,title:'Id'},
    		{ data: 'Puppy_Name' ,title:'Pup name'},
    		{ data: 'LogLevel_idLevel' ,title:'Level'},
            { data: 'Job' ,title:'Job'},
    		]
    	});

    $(tasks_table.table().header().rows).clone(true).appendTo( tasks_table.table().header() );
    $(tasks_table.table().header().rows[1].cells).each( function (i) {
        var title = $(this).text();
        $(this).html( '<input class="form-control form-control-sm" type="text" placeholder="Search '+title+'" />' );
 
        $( 'input', this ).on( 'keyup change', function () {
            if ( tasks_table.column(i).search() !== this.value ) {
                tasks_table
                    .column(i)
                    .search( this.value )
                    .draw();
            }
        } );
    } );

    tasks_table.draw()
}
</script>